---
title: "Course Syllabus (Spring 2017)"
author: "Z620: Quantitative Biodiversity, Indiana University"
output: pdf_document
geometry: margin=2.54cm
---

Biodiversity refers to the variation among life and extends from within populations to across species and entire ecosystems. Due to one of the most rapid rates of extinction  in Earth's history, the world is currently facing a biodiversity crisis. Consequently, it is imperative that we have an understanding of biodiversity and how to characterize and quantify it.

### Course summary
This course will introduce students to the concepts, patterns, metrics, and tools that are common to the study of biodiversity. Each class meeting will consist of a short lecture followed by computational exercises designed to analyze aspects of biodiversity using data from tree, bird, mammal, and microbial systems. Students will learn how to calculate diversity metrics, generate and quantify diversity relationships, visualize multivariate data, and test hypotheses with an array of statistical techniques. We will learn how to map traits to phylogenetic trees and make inferences about the phylogenetic structure of communities. Concepts related to taxonomic and phylogenetic diversity will be extended to understand spatial and temporal dynamics. Students will be introduced to modern statistical computing and graphics environments, as well as the version control tools Git and GitHub. The class will culiminate with student-led team projects. 

### Course Director
Dr. Jay T. Lennon<br>
261B Jordan Hall (office)<br>
812-856-0962 (office phone)<br>
[lennonj@indiana.edu](mailto:lennonj@indiana.edu?Subject=Quantitative%20Biodiversity%202017)<br>

### Other Instructors
Dr. Ken Locey<br>
238 Jordan Hall (office)<br>
[kjlocey@indiana.edu](mailto:kjlocey@indiana.edu?Subject=Quantitative%20Biodiversity%202017)<br>

Will Shoemaker <br>
238 Jordan Hall (office)<br>
[rshoema@indiana.edu](mailto:wrshoema@indiana.edu?Subject=Quantitative%20Biodiversity%202017)<br>

Nathan Wisnoski <br>
238 Jordan Hall (office)<br>
[wisnoski@indiana.edu](mailto:wisnoski@indiana.edu?Subject=Quantitative%20Biodiversity%202017)<br>

### Class meetings
9:30-12:00 Friday, room 155 in the [Public Health (PH) Building](http://goo.gl/LJb3W5), Janurary 13 - March 3, 2017


### Recommended Textbooks 
* Measuring Biological Diversity, Magurran (2004) – ([available online](http://goo.gl/MgKtXs) and on reserve in Life Science Library)
* Biological Diversity, Magurran and McGill (2011) – ([available online](http://goo.gl/gtsFph) and on reserve in Life Science Library)
* Numerical Ecology, Legendre and Legendre (2013) – ([available online](http://www.sciencedirect.com/science/bookseries/01678892/24))
* Introductory Statistics with R, Dalgard (2008) – ([available online](http://link.springer.com/book/10.1007/978-0-387-79054-1))
* Numerical Ecology with R, Borcard, Gillet, & Legendre (2011) – ([available online](http://link.springer.com/book/10.1007/978-1-4419-7976-6))
* Functional and Phylogenetic Ecology in R, Swenson (2014) – ([available online](http://link.springer.com/book/10.1007/978-1-4614-9542-0))
* Phylogenies in Ecology, Cadotte and Davies (2016) - ([available online](https://goo.gl/kWq457))
* Pro Git, Chacon and Straub (2014) ([available online](https://goo.gl/zF9tNr))

### Computational Approaches to Biodiversity Using R And GitHub
In this course, we will be using [R](http://www.r-project.org/) and [GitHub](https://github.com/) as complimentary tools for learning quantitative biodiversity. R is a free, open-source programming language that is widely used for data visualization and statistics. Specifically, [RStudio](http://www.rstudio.com/) is an integrated development environment (IDE) that will allow us to interface with other packages, including [Markdown](http://en.wikipedia.org/wiki/Markdown) and [LaTeX](http://www.latex-project.org/). Last, we will be using GitHub as a version control system to track, record, and recover changes throughout the history of a project. 
GitHub is the premier tool for collaborative and social development of computing-based projects, allowing instructors, students, and collaborators to develop a project (or class) from remote locations. We will use [GitHub](https://github.com/) to host course material including this syllabus, code, and exercises. Each student will have their own private GitHub repository and will use GitHub to store and submit their work.

### Other Course Resources
We will be assembling course literature, including reading assignments in our [Quantiative Biodiversity Mendeley group](http://goo.gl/wWXVtH). 
PDF versions of required papers, along with slides from class lectures will be posted on the IU's learning management system, [Canvas](http://goo.gl/tTmEe7). 
We will also use [etherpad](http://en.wikipedia.org/wiki/Etherpad), which is a real-time editor that will facilitate collaboration and problem-solving inside and outside the classroom. 

### Learning Objectives
**Quantitative Biodiversity is organized around the following learning objectives**<br>
&nbsp;&nbsp;***Upon completion of the course, students will be able to:***<br>
&nbsp;&nbsp;&nbsp;&nbsp;1. Identify and discuss core concepts of biodiversity<br>
&nbsp;&nbsp;&nbsp;&nbsp;2. Quantify and compare measures of taxonomic diversity within and among samples<br>
&nbsp;&nbsp;&nbsp;&nbsp;3. Quantify the distribution of traits and species in a phylogenetic context<br>
&nbsp;&nbsp;&nbsp;&nbsp;4. Evaluate biodiversity in spatial and temporal contexts<br>
&nbsp;&nbsp;&nbsp;&nbsp;5. Use the R programming language to analyze and visualize biodiversity data<br>
&nbsp;&nbsp;&nbsp;&nbsp;6. Use GitHub for conducting and managing reproducible research projects<br>

### Student Assessment
* **Assignments:** Students will be assigned in-class exercises, which will have problem sets that need to be submitted via GitHub.
* **Reading:** Students will be expected to read assigned papers from the primary literature prior to class meetings. 
* **Group project:** Students will be assigned to groups and will conduct an independent project that will be presented to the class.
* **Participation:** Students will need to attend and actively engage in discussion and computational exercises.

### Academic Integrity
As a student at IU, you are expected to adhere to the standards and policies detailed in the [Code of Student Rights, Responsibilities, and Conduct](http://www.iu.edu/~code/). 
When you submit an assignment with your name on it in this course, you are signifying that the work contained therein is all yours, unless otherwise cited or referenced. 
Similar standards are assumed for presentations and the generation of web-based media. 
Any ideas or materials taken from another source for either written or oral use must be fully acknowledged. 
If you are unsure about the expectations for completing an assignment, be sure to seek clarification beforehand. 
All suspected violations of the Code will be handled according to University policies. 
Sanctions for academic misconduct may include a failing grade on the assignment, reduction in your final grade, a failing grade in the course, among other possibilities, and must include a report to the Dean of Students.

### Attendance
Given the small number of class meetings, attendence is required. Absences will negatively affect a student's grade. Any conflicts should be communicated to the instructor as early as possible, preferable before the beginning of the semester.

### Special Needs
Please contact the course director as soon as possible if you have a documented disability that will interfere your performance of the activities planned for the class.


## Schedule

### Week 0
**Introduction to the computing environment**<br>
Prior to our first class meeting, students will install software, conduct basic exercises, and read introductory material. 

[Week 0 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week0)<br>


### Week 1
**Introduction to Quantitative Biodiversity**<br>

What is biodiversity and why do we study it? After introducing the course, we will provide an overview of GitHub and R. Laboratory exercises will include an exercise in GitHub followed by exercises in R such as data manipulations, plotting, and simple statistics. 

[Week 1 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week1)<br>


### Week 2
**Diversity Within a Sample (i.e., alpha-Diversity)**<br>
We will begin by introducing one the primary ecological data structures: the site-by-species matrix. From this, we will derive the core components of diversity: richness and evenness. We will integrate richness and evenness components by covering diversity metrics and the species abundance distribution (SAD).

[Week 2 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week2-Alpha)

### Week 3
**Diversity Among Samples (i.e., beta-Diversity)**<br>
We will learn how to quantify diversity among samples (beta-diversity). We will then focus on the visualization of beta-diversity, which will include heatmaps, hierarchical clustering, and multivariate ordination. Last, we will highlight statistical approaches that allow one to test hypotheses about beta-diversity. 

[Week 3 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week3-Beta)

### Week 4 
**Spatial divesity**<br>
We will introduce ways to quantify the dispersion and aggregation of species in space. We will then learn about some of the major geographic patterns of biodiversity, including the spatial species abudnance distribution (sSAD), distance decay (DD), and the species area relationship (SAR). We will conclude by using variance partitioning to quantify the contribution of geographic distance and the enviroment to species distributions. 

[Week 4 materils](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week4-Spatial)

### Week 5 
**Temporal divesity**<br>
We will introduce ways to quantify biodiversity through time. This will include ways of making infereces from non-independent, autocorrelated univariate and multivariate data. We will addresss ways to quantitatively link temporal biodiversity data to corresponding enviromental data while addressing questions of stability. 

[Week 5 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week5-Temporal)

### Week 6
**Phylogenetic Diversity: Traits**<br>
We will learn how to make phylogenetic trees in R. After this, we will use contributed R packages to map traits onto trees, peform phylogenteically independent contrasts, and test for phylogenetic signal. 

[Week 6 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week6-PhyloTraits)

### Week 7
**Phylogenetic Diversity: Communities**<br>
We will continue to learn about the intergration of phylogenetic for questions related to biodiversity. Specifically, we will think about phylogenetic community ecology, by introducing tools such as unifrac, net-relatedness index (NRI), and nearest taxon index (NTI).

[Week 7 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week7-PhyloCom)

### Week 8
**Projects and Synthesis: GitOn**<br>
We will use this class period for student presentations of their independent projects while recapping major concepts and tools, in addition to "big data" aproaches to addressing global biodiversity issues. . 

[Week 8 materials](https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week8-GitOn)


