---
title: "4\\. Software Installation Guide"
author: "Z620: Quantitative Biodiversity, Indiana University"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

Quantitative Biodiveristy (QB) requires that you install certain software on your personal computers, including R, RStudio, Git, and LaTeX.
This guide describes the software and how to install it.

##1) R

We will use R to manipulate, visualize, and statistically analyze data.
We will install the latest version of R (v 3.5.2; "Eggshell Igloo") using the following insructions:

1. Open a web browser and naviate to the IU CRAN mirror: http://ftp.ussg.iu.edu/CRAN/
2. Please select your operating system (Mac, Windows, Linux)
    For Windows Users: install the `base package`
    For Mac Users: install the package for your current version of OS X. You can find out what version is installed by going to the Apple menu and choosing "About This Mac". The version number of OS X you are using appears directly below the words "OS X."
3. The default installation options are recommended for most users

**Mac users please read**:
    The most recent versions of R no longer come packaged with an X11 graphics device.
    Instead, it relies on the program XQuartz for generating plots, etc.
    If you do not already have XQuarts installed, you will need to do this.
    You can download XQuartz v2.7.11 from the following site: http://xquartz.macosforge.org/landing/

##2) Git

We will be using Git as the version control software to manage our text and code.
If you already use Git, please ensure you are using the most up-to-date version.
If you do not have Git yet installed, please do the following:

1. Open a web browser and naviate to git-scm.com/download/
2. Select the appropriate operating system.
3. The download should start automatically.
4. Open the installer and follow the onscreen directions.

  **On Mac**: You will need to make sure you have Xcode Command Line Tools installed.
  To test this type `which g++` at the command line.
  If you get `/usr/bin/g++` as a reply, then you are ready to move on.
  
  **On Windows**: This process will install Git Bash (msysGit). 
  During installation, you will be asked to adjust your **PATH environment variable**.
  To provide you with the most flexibility, we recommend that you select the option to "Use Git from the Windows Command Prompt".
  In addition, we recommend that during installation you select "Use OpenSSH" for your secure shell client with GitBash.
  
  During installation, you will be asked how to configure the line-ending conversions
  **On Mac**: We recommend "Checkout as-is, commit Unix-style line endings"
  **On Windows**: We recommend "Checkout Windows-style, commit Unix-style line endings"

##3)  RStudio

We will be using RStudio as the development environment to conduct exercises in R. 
We will also use RStudio to edit and create markdown files. 
If you do not have a current RStudio version installed on your computer (v 1.0.1 or later), please do the following:

1. Open a web browser and naviate to http://www.rstudio.com/products/rstudio/download/
2. Select and download the appropriate installer for your operating system (Windows, Mac, Linux)
3. Open the installer and follow the onscreen directions
4. The default installation options are recommended for most users

##4)  LaTex

Behind the scences, we will be using the typsettings systems LaTeX.
LaTeX will be used by RStudio and the R package `Knitr` to convert our RMarkdown files (.Rmd) into professional-quality PDF files. 
This will happen each time we use the "Knit" button in RStudio.
This means that we need to have LaTeX installed, along with a few other packages. 
If you do not have LaTeX installed on your computer, please do the following: 

**On a Mac**:

1. Install Basic Tex: https://tug.org/mactex/morepackages.html
2. Note: this will require you to run the commands below (to install `framed` and `titling`).

**On a PC**:

1. Install Basic MiKTeX: http://miktex.org/download.
2. Note: you need to use the MiKTeX package manager to download required style guides.
3. Add folder containing MiKTeX biniaries to your **PATH environment variable**

By default, RStudio uses style guides to format our PDF documents. 
These style guides include framed.sty and titling.sty.
We have found that not all LaTeX installations include these style guides.
If you do not have them, you will get an error message when you "Knit".
To fix this, you need to install the required files.
For instructions to add MiKTeX binaries to **PATH environment variable** see https://stackoverflow.com/questions/47911135/r-sweave-no-tex-installation-detected.

**On a Mac**:
Type the following in terminal:
    
```sh
tlmgr init-usertree
tlmgr --usermode install framed
tlmgr --usermode install titling
```

**On a PC**:
You have two options:
  
1. Open the MikTeX package manager from Start.
2. Search for and install the following: framed, titling
    
    OR
  
1. Type the following in command line (or GitBash):

```sh        
mpm --install framed
mpm --install titling
```
